import { Navigate, Route, Routes } from 'react-router-dom';
import AdminRoute from './components/AdminRoute';
import ProtectedRoute from './components/ProtectedRoute';
import AppLayout from './layouts/AppLayout';
import AdminAnalyticsPage from './pages/AdminAnalyticsPage';
import AdminCoursesPage from './pages/AdminCoursesPage';
import AdminDashboardPage from './pages/AdminDashboardPage';
import CourseDetailPage from './pages/CourseDetailPage';
import CoursesPage from './pages/CoursesPage';
import DashboardPage from './pages/DashboardPage';
import LandingPage from './pages/LandingPage';
import LearningPathPage from './pages/LearningPathPage';
import LoginPage from './pages/LoginPage';
import OnboardingPage from './pages/OnboardingPage';
import RegisterPage from './pages/RegisterPage';
import SavedCoursesPage from './pages/SavedCoursesPage';
import SkillGapPage from './pages/SkillGapPage';
const App = () => <Routes><Route element={<AppLayout/>}><Route path="/" element={<LandingPage/>}/><Route path="/login" element={<LoginPage/>}/><Route path="/register" element={<RegisterPage/>}/><Route path="/courses" element={<CoursesPage/>}/><Route path="/courses/:id" element={<CourseDetailPage/>}/><Route element={<ProtectedRoute/>}><Route path="/onboarding" element={<OnboardingPage/>}/><Route path="/dashboard" element={<DashboardPage/>}/><Route path="/learning-path" element={<LearningPathPage/>}/><Route path="/skill-gap" element={<SkillGapPage/>}/><Route path="/saved" element={<SavedCoursesPage/>}/></Route><Route element={<AdminRoute/>}><Route path="/admin" element={<AdminDashboardPage/>}/><Route path="/admin/courses" element={<AdminCoursesPage/>}/><Route path="/admin/analytics" element={<AdminAnalyticsPage/>}/></Route><Route path="*" element={<Navigate to="/" replace/>}/></Route></Routes>;
export default App;
